### ISSUE TITLE
Init NestJS application

### ISSUE THREAD

**Issue by louiiuol** [louiiuol/lmc-api#1]
# Contexte 📝

Generate API with NestJs to handle business logic and persist entities' states in the database.

# TODO 💪

- [x] Generate NestJs API named `lmc-api`

- [x] Generate database table named `claires-method`

- [x] Configure connexion with database

- [x] Generable tables based on entity and data to ease testing different use cases

# Additional context 🔎

- [NestJS - get started](https://docs.nestjs.com/first-steps)
- [Automapper](https://automapperts.netlify.app/docs/nestjs)
- [TypeORM](https://docs.nestjs.com/techniques/database)
- [Seed Database](https://medium.com/the-crowdlinker-chronicle/seeding-databases-using-nestjs-cd6634e8efc5)
- [Dynamic modules](https://docs.nestjs.com/modules#dynamic-modules)
