### ISSUE TITLE
Administration de la librairie

### ISSUE THREAD

**Issue by louiiuol** [louiiuol/lmc-api#16]
## Contexte

> La librarie doit pouvoir être gérée depuis l'API. Les admins de l'application pourront ainsi l'éditer au fur et à mesure de l'année.

## TODO

- [ ] Gestion de l'import de PDF sur le serveur
- [ ] Gestion des fichiers sur le serveurs; ajout, édition et suppression de fichiers
- [ ] Création de liens permettant le téléchargement de PDF (unitaire et groupés)
- [ ] Associer les PDFsur le serveur avec les leçons en base de donnée
- [ ] La ressource `GET /api/courses` renverra désormais des liens précédemment créés.

### Resources

> protégée par authentification (admin)

- [ ] Créer une leçon  `POST /api/courses` 
- [ ] Editer une leçon  `PUT /api/courses/{uuid}`
- [ ] Supprimer une leçon  `DELETE /api/courses/{uuid}`
